# Generated by Django 6.1 on 2026-09-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutBrand',
            new_name='ProductBrand',
        ),
    ]
